### ISSUE TITLE
CB3S error read dump

### ISSUE THREAD

**Issue by Liionboy** [openshwprojects/OpenBK7231T_App#581]
Hello,

I am trying to read dump from a Led Controler with CB3S and i get this error:

root@adrian-huawei-d16:~/tuya_led_controller# bk7231tools read_flash -d /dev/ttyUSB0 -s 0 -l 0x200000 dump_led_control.bin
Traceback (most recent call last):
  File "/usr/local/bin/bk7231tools", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/bk7231tools/__main__.py", line 468, in cli
    with closing(connect_device(args.device, args.baudrate, args.timeout, args.debug)) as device:
  File "/usr/local/lib/python3.10/dist-packages/bk7231tools/__main__.py", line 270, in connect_device
    s.connect()
  File "/usr/local/lib/python3.10/dist-packages/bk7231tools/serial/__init__.py", line 38, in connect
    if not self.wait_for_link(self.link_timeout):
  File "/usr/local/lib/python3.10/dist-packages/bk7231tools/serial/cmd_chip.py", line 38, in wait_for_link
    response: BkLinkCheckResp = self.command(command)
  File "/usr/local/lib/python3.10/dist-packages/bk7231tools/serial/protocol.py", line 207, in command
    data = self.read(until=PACKET_RESP_PREAMBLE)
  File "/usr/local/lib/python3.10/dist-packages/bk7231tools/serial/protocol.py", line 169, in read
    data = self.serial.read_until(until)
  File "/usr/local/lib/python3.10/dist-packages/serial/serialutil.py", line 663, in read_until
    c = self.read(1)
  File "/usr/local/lib/python3.10/dist-packages/serial/serialposix.py", line 595, in read
    raise SerialException(
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

Thanks

**Comment by Liionboy** [comment]
is worked, can't reset with CEN only from button
